// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo50GjDuWq2cESLV2SzYhBd1t5L5rq9C0',
    appId: '1:1010634727730:web:0706e459dbf0b572e8772b',
    messagingSenderId: '1010634727730',
    projectId: 'notification-pusher-27270',
    authDomain: 'notification-pusher-27270.firebaseapp.com',
    storageBucket: 'notification-pusher-27270.appspot.com',
    measurementId: 'G-Y09QQ43LSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMgpENYjleHimIgCLSSMuyNlW6GF1QdA',
    appId: '1:1010634727730:android:f5408ed3722edf5ae8772b',
    messagingSenderId: '1010634727730',
    projectId: 'notification-pusher-27270',
    storageBucket: 'notification-pusher-27270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bezmWE5Hp4DH57nrYLjBJVNuPYDSP2Q',
    appId: '1:1010634727730:ios:40bd87817e25124fe8772b',
    messagingSenderId: '1010634727730',
    projectId: 'notification-pusher-27270',
    storageBucket: 'notification-pusher-27270.appspot.com',
    iosBundleId: 'com.example.masterbagasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bezmWE5Hp4DH57nrYLjBJVNuPYDSP2Q',
    appId: '1:1010634727730:ios:cb81df1bb696248fe8772b',
    messagingSenderId: '1010634727730',
    projectId: 'notification-pusher-27270',
    storageBucket: 'notification-pusher-27270.appspot.com',
    iosBundleId: 'com.example.masterbagasi.RunnerTests',
  );
}
